monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: info
            handler: nested
            channels: [ "!event", "!doctrine", "!security" ]
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [ "!event", "!doctrine" ]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        security:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.security.log"
            channels: ["security"]
            max_level: info
        swift:
            type: swift_mailer
            from_email: "errors@personal-management-system.pl"
            to_email: '%env(APP_EMERGENCY_EMAILS_RECEIVER_EMAIL)%'
            subject: '[%project.name%] An Error Occurred!'
            level: emergency
            formatter:  monolog.formatter.html
            content_type: text/html
